// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace CarRentalWebAPI.Models;

[Index("Email", Name = "UQ__Applicat__A9D10534AE2E3DED", IsUnique = true)]
public partial class ApplicationUser:IdentityUser
{
    [Required]
    [StringLength(100)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(100)]
    public string LastName { get; set; }

    public int UserType { get; set; }

    public bool IsVerified { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastLogin { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    [InverseProperty("Owner")]
    public virtual ICollection<Car> Cars { get; set; } = new List<Car>();

    [InverseProperty("User")]
    public virtual ICollection<UserDocument> UserDocuments { get; set; } = new List<UserDocument>();

    [ForeignKey("UserType")]
    [InverseProperty("ApplicationUsers")]
    public virtual UserType UserTypeNavigation { get; set; }
}