// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CarRentalWebAPI.Models;

public partial class BookingStatus
{
    [Key]
    public int StatusId { get; set; }

    [Required]
    [StringLength(50)]
    public string StatusName { get; set; }

    [InverseProperty("BookingStatusNavigation")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}