// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CarRentalWebAPI.Models;

[Index("CarId", Name = "IX_Bookings_Car")]
[Index("StartDate", "EndDate", Name = "IX_Bookings_StartDate_EndDate")]
[Index("UserId", Name = "IX_Bookings_User")]
public partial class Booking
{
    [Key]
    public Guid BookingId { get; set; }

    [Required]
    public string UserId { get; set; }

    public Guid CarId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime EndDate { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal TotalPrice { get; set; }

    public int BookingStatus { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDate { get; set; }

    [ForeignKey("BookingStatus")]
    [InverseProperty("Bookings")]
    public virtual BookingStatus BookingStatusNavigation { get; set; }

    [ForeignKey("CarId")]
    [InverseProperty("Bookings")]
    public virtual Car Car { get; set; }

    [InverseProperty("Booking")]
    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    [InverseProperty("Booking")]
    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    [ForeignKey("UserId")]
    [InverseProperty("Bookings")]
    public virtual ApplicationUser User { get; set; }
}