// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CarRentalWebAPI.Models;

[Index("LicensePlate", Name = "UQ__Cars__026BC15C85E7F6FB", IsUnique = true)]
public partial class Car
{
    [Key]
    public Guid CarId { get; set; }

    [Required]
    [StringLength(450)]
    public string OwnerId { get; set; }

    [Required]
    [StringLength(500)]
    public string Model { get; set; }

    public int Year { get; set; }

    [Required]
    [StringLength(20)]
    public string LicensePlate { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal DailyPrice { get; set; }

    public bool IsAvailable { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDate { get; set; }

    public bool IsDeleted { get; set; }

    public double CarCurrentRate { get; set; }

    public int NumberOfReviews { get; set; }

    [InverseProperty("Car")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    [ForeignKey("OwnerId")]
    [InverseProperty("Cars")]
    public virtual ApplicationUser Owner { get; set; }
}