// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CarRentalWebAPI.Models;

public partial class DocumentType
{
    [Key]
    [Column("DocumentType")]
    public int DocumentType1 { get; set; }

    [Required]
    [StringLength(50)]
    public string TypeName { get; set; }

    [InverseProperty("DocumentTypeNavigation")]
    public virtual ICollection<UserDocument> UserDocuments { get; set; } = new List<UserDocument>();
}