// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CarRentalWebAPI.Models;

[Index("StripePaymentId", Name = "IX_Payments_StripeId")]
[Index("StripePaymentId", Name = "UQ__Payments__4DBD220C0B71D024", IsUnique = true)]
public partial class Payment
{
    [Key]
    public Guid PaymentId { get; set; }

    public Guid BookingId { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal Amount { get; set; }

    public int PaymentStatus { get; set; }

    [Required]
    [StringLength(255)]
    public string StripePaymentId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime PaymentDate { get; set; }

    [ForeignKey("BookingId")]
    [InverseProperty("Payments")]
    public virtual Booking Booking { get; set; }
}