// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CarRentalWebAPI.Models;

public partial class UserType
{
    [Key]
    [Column("UserType")]
    public int UserType1 { get; set; }

    [Required]
    [StringLength(50)]
    public string TypeName { get; set; }

    [InverseProperty("UserTypeNavigation")]
    public virtual ICollection<ApplicationUser> ApplicationUsers { get; set; } = new List<ApplicationUser>();
}